### ISSUE TITLE
Handle edge cases of Pocket API

### ISSUE THREAD

**Issue by Coteh** [Coteh/gyroid#10]
One I can think of off the top of my head that I've encountered:
- If Retrieve returns a status of 2, then it appears to indicate that I have gone past the last article (ie. I set an offset greater than total number of articles)

Create new issues for some of these types of edge cases if necessary. If this project is switching to go-pocket (#7), then we might not need to do anything if that library already handles such cases.

# TODO
- [ ] Find edge cases of Pocket API to consider
    - [ ] For each one, either make a new issue or fix it here
- [ ] Figure out if go-pocket is being adopted (#7)
