### ISSUE TITLE
Prompt user to add article when end of article list reached

### ISSUE THREAD

**Issue by Coteh** [Coteh/gyroid#20]
Definitely a UI oversight on my end 😅 When the user reaches the end of their list (or their list is empty), give them a prompt for whether they would like to add an article.

# TODO
- [x] Add prompt asking user to add article
    - [x] If yes, open up add article prompt
    - [x] If no, exit cli
- [x] When user reaches end of list, prompt
- [x] When user has no articles, prompt
- ~Have this configurable in `config.yml`: `end-of-list-add` (true or false)~
- [x] Complete testing
- [x] Add a pointer to start of articlesList for article loop, or block this task on article queue
