### ISSUE TITLE
Show expected read time alongside Pocket article in listing

### ISSUE THREAD

**Issue by Coteh** [Coteh/gyroid#3]
Double check whether there's a property from the `Retrieve` endpoint that contains this. If not, a rough estimate can be calculated using the word count and the average number of words per minute that an average person reads.

# TO-DO
- [x] Divide word count by average wpm (similar to https://github.com/SteveCohen/Pocket-ReadingTimeTagger)
- [x] Print out estimated reading time alongside article result

**Comment by Coteh** [comment]
# TO-DO
- [ ] Divide word count by average wpm (similar to https://github.com/SteveCohen/Pocket-ReadingTimeTagger)
