### ISSUE TITLE
Remove clipboard suggestion once it's added

### ISSUE THREAD

**Issue by Coteh** [Coteh/gyroid#30]
Clipboard suggestion should no longer be suggested once it's added, unless a new URL is copied into the clipboard.

# TODO
- [x] Save clipboard item to clipboard manager (or somewhere else)
- [x] Add flag to clipboard manager to indicate that user used clipboard suggestion
- [x] If user adds from clipboard, set flag to true
- [x] If URL from clipboard is different from saved value, then replace the saved value with new clipboard URL and set flag to false

**Comment by Coteh** [comment]
Fixed in #37, no flag needed.
