### ISSUE TITLE
Create mock Pocket API server for development

### ISSUE THREAD

**Issue by Coteh** [Coteh/gyroid#35]
Thought I made an issue for this already, but guess I didn't. 😅 

# TODO
- [ ] Create mock server that mimics `get`, `modify`, `add`, and auth endpoints
- [ ] Populate server with fake article data
- [ ] Set API URL of dev gyroid to mock server address
    - [ ] Will need to move out API URL to be a config value (either in `.env` or `config.yml`)
