### ISSUE TITLE
Copy article link to clipboard

### ISSUE THREAD

**Issue by Coteh** [Coteh/gyroid#39]
I would like to be able to easily copy a link in the refinement list to the clipboard, as sometimes I would like to take an article off of my Pocket list and into another tool (Todoist, Trello, etc.) right away.

## TODO
- [x] Add new CLI option to copy article link
- [x] Extend `Clipboard` class to copy given string
- [x] When CLI option is activated, pass article link into new `Clipboard` method

**Comment by Coteh** [comment]
Added in #44
