### ISSUE TITLE
Get a total count of posts

### ISSUE THREAD

**Issue by Coteh** [Coteh/gyroid#5]
Ensure that the async calls we make to Pocket API can correctly return all articles from a user's Pocket list as well as report the total count of articles. Since it's async (ie. in goroutines) we don't have to get this data right away before displaying the first article to the user.

# TODO
- [ ] Indicate to cli somehow that all articles have finished loading
- [ ] Once cli is indicated all articles are done loading, get the length of the articles array (this will be the number of _untagged_, or _unrefined_ articles)
- [ ] Print this somehow???
    - [ ] Should probably be on top or on bottom of article printout
    - [ ] What should print when we're still waiting for all articles to load?
- [ ] When user adds article, increment the number of unrefined articles by 1

**Comment by Coteh** [comment]
# TODO
- [ ] Indicate to cli somehow that all articles have finished loading
- [ ] Once cli is indicated all articles are done loading, get the length of the articles array (this will be the number of _untagged_, or _unrefined_ articles
- [ ] Print this somehow???
    - [ ] Should probably be on top or on bottom of article printout
    - [ ] What should print when we're still waiting for all articles to load?
- [ ] When user adds article, increment the number of unrefined articles by 1
